In [2]:
import pandas as pd
df = pd.read_csv("ted_main.csv", encoding = "utf-8")
df

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2545,17,"Between 2008 and 2016, the United States depor...",476,TED2017,1496707200,4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,1,1505851216,"[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,https://www.ted.com/talks/duarte_geraldino_wha...,450430
2546,6,How can you study Mars without a spaceship? He...,290,TED2017,1492992000,3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,1,1505919737,"[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,https://www.ted.com/talks/armando_azua_bustos_...,417470
2547,10,Science fiction visions of the future show us ...,651,TED2017,1492992000,1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,1,1506006095,"[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,https://www.ted.com/talks/radhika_nagpal_what_...,375647
2548,32,In an unmissable talk about race and politics ...,1100,TEDxMileHigh,1499472000,1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,1,1506024042,"[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,419309
2549,8,With more than half of the world population li...,519,TED2017,1492992000,1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,1,1506092422,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,https://www.ted.com/talks/karoliina_korppoo_ho...,391721

In [3]:
df.shape

(2550, 17)

In [8]:
df[['comments', 'description', 'url']]

,comments,description,url
0,4553,Sir Ken Robinson makes an entertaining and pro...,https://www.ted.com/talks/ken_robinson_says_sc...
1,265,With the same humor and humanity he exuded in ...,https://www.ted.com/talks/al_gore_on_averting_...
2,124,New York Times columnist David Pogue takes aim...,https://www.ted.com/talks/david_pogue_says_sim...
3,200,"In an emotionally charged talk, MacArthur-winn...",https://www.ted.com/talks/majora_carter_s_tale...
4,593,You've never seen data presented like this. Wi...,https://www.ted.com/talks/hans_rosling_shows_t...
...,...,...,...
2545,17,"Between 2008 and 2016, the United States depor...",https://www.ted.com/talks/duarte_geraldino_wha...
2546,6,How can you study Mars without a spaceship? He...,https://www.ted.com/talks/armando_azua_bustos_...
2547,10,Science fiction visions of the future show us ...,https://www.ted.com/talks/radhika_nagpal_what_...
2548,32,In an unmissable talk about race and politics ...,https://www.ted.com/talks/theo_e_j_wilson_a_bl...
2549,8,With more than half of the world population li...,https://www.ted.com/talks/karoliina_korppoo_ho...

In [9]:
df.iloc[0]

comments                                                           4553
description           Sir Ken Robinson makes an entertaining and pro...
duration                                                           1164
event                                                           TED2006
film_date                                                    1140825600
languages                                                            60
main_speaker                                               Ken Robinson
name                          Ken Robinson: Do schools kill creativity?
num_speaker                                                           1
published_date                                               1151367060
ratings               [{'id': 7, 'name': 'Funny', 'count': 19645}, {...
related_talks         [{'id': 865, 'hero': 'https://pe.tedcdn.com/im...
speaker_occupation                                      Author/educator
tags                  ['children', 'creativity', 'culture', 'dance',...
title                                       Do schools kill creativity?
url                   https://www.ted.com/talks/ken_robinson_says_sc...
views                                                          47227110
Name: 0, dtype: object

In [10]:
df.iloc[10:15]

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
10,79,"Accepting his 2006 TED Prize, Cameron Sinclair...",1414,TED2006,1140912000,27,Cameron Sinclair,Cameron Sinclair: My wish: A call for open-sou...,1,1153786260,"[{'id': 3, 'name': 'Courageous', 'count': 169}...","[{'id': 1749, 'hero': 'https://pe.tedcdn.com/i...","Co-founder, Architecture for Humanity","['activism', 'architecture', 'collaboration', ...",My wish: A call for open-source architecture,https://www.ted.com/talks/cameron_sinclair_on_...,1211416
11,55,Jehane Noujaim unveils her 2006 TED Prize wish...,1538,TED2006,1140912000,20,Jehane Noujaim,Jehane Noujaim: My wish: A global day of film,1,1153786260,"[{'id': 1, 'name': 'Beautiful', 'count': 70}, ...","[{'id': 2228, 'hero': 'https://pe.tedcdn.com/i...",Filmmaker,"['TED Prize', 'art', 'culture', 'entertainment...",My wish: A global day of film,https://www.ted.com/talks/jehane_noujaim_inspi...,387877
12,71,"Accepting the 2006 TED Prize, Dr. Larry Brilli...",1550,TED2006,1140652800,24,Larry Brilliant,Larry Brilliant: My wish: Help me stop pandemics,1,1153786260,"[{'id': 8, 'name': 'Informative', 'count': 188...","[{'id': 1153, 'hero': 'https://pe.tedcdn.com/i...","Epidemiologist, philanthropist","['TED Prize', 'collaboration', 'disease', 'ebo...",My wish: Help me stop pandemics,https://www.ted.com/talks/larry_brilliant_want...,693341
13,242,"Jeff Han shows off a cheap, scalable multi-tou...",527,TED2006,1139184000,27,Jeff Han,Jeff Han: The radical promise of the multi-tou...,1,1154391060,"[{'id': 9, 'name': 'Ingenious', 'count': 1014}...","[{'id': 685, 'hero': 'https://pe.tedcdn.com/im...",Human-computer interface designer,"['demo', 'design', 'interface design', 'techno...",The radical promise of the multi-touch interface,https://www.ted.com/talks/jeff_han_demos_his_b...,4531020
14,99,"Nicholas Negroponte, founder of the MIT Media ...",1057,TED2006,1140652800,25,Nicholas Negroponte,Nicholas Negroponte: One Laptop per Child,1,1154391060,"[{'id': 3, 'name': 'Courageous', 'count': 83},...","[{'id': 2043, 'hero': 'https://pe.tedcdn.com/i...",Tech visionary,"['children', 'design', 'education', 'entrepren...",One Laptop per Child,https://www.ted.com/talks/nicholas_negroponte_...,358304

In [11]:
df.head(5)

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869

In [12]:
df.tail(5)

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
2545,17,"Between 2008 and 2016, the United States depor...",476,TED2017,1496707200,4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,1,1505851216,"[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,https://www.ted.com/talks/duarte_geraldino_wha...,450430
2546,6,How can you study Mars without a spaceship? He...,290,TED2017,1492992000,3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,1,1505919737,"[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,https://www.ted.com/talks/armando_azua_bustos_...,417470
2547,10,Science fiction visions of the future show us ...,651,TED2017,1492992000,1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,1,1506006095,"[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,https://www.ted.com/talks/radhika_nagpal_what_...,375647
2548,32,In an unmissable talk about race and politics ...,1100,TEDxMileHigh,1499472000,1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,1,1506024042,"[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,419309
2549,8,With more than half of the world population li...,519,TED2017,1492992000,1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,1,1506092422,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,https://www.ted.com/talks/karoliina_korppoo_ho...,391721

In [14]:
df[['comments', 'description', 'duration']].iloc[:5]

   comments                                        description  duration
0      4553  Sir Ken Robinson makes an entertaining and pro...      1164
1       265  With the same humor and humanity he exuded in ...       977
2       124  New York Times columnist David Pogue takes aim...      1286
3       200  In an emotionally charged talk, MacArthur-winn...      1116
4       593  You've never seen data presented like this. Wi...      1190

In [17]:
test = df.iloc[:3]
test

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292

In [19]:
test[ [True, False, True]]

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292

In [22]:
bool_filter = df['description'].str.contains('Sir')  #str 字串list #對每個元素做布林判斷
bool_filter

0        True
1       False
2       False
3       False
4       False
        ...
2545    False
2546    False
2547    False
2548    False
2549    False
Name: description, Length: 2550, dtype: bool

In [23]:
df[bool_filter]

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
15,325,Violinist Sirena Huang gives a technically bri...,1481,TED2006,1140652800,31,Sirena Huang,Sirena Huang: An 11-year-old's magical violin,1,1154995860,"[{'id': 1, 'name': 'Beautiful', 'count': 1671}...","[{'id': 2273, 'hero': 'https://pe.tedcdn.com/i...",Violinist,"['entertainment', 'music', 'performance', 'vio...",An 11-year-old's magical violin,https://www.ted.com/talks/sirena_huang_dazzles...,2702470
54,203,"Speaking as both an astronomer and ""a concerne...",1046,TEDGlobal 2005,1121299200,29,Martin Rees,Martin Rees: Is this our final century?,1,1168992660,"[{'id': 1, 'name': 'Beautiful', 'count': 214},...","[{'id': 167, 'hero': 'https://pe.tedcdn.com/im...",Astrophysicist,"['astronomy', 'climate change', 'complexity', ...",Is this our final century?,https://www.ted.com/talks/martin_rees_asks_is_...,2121177
692,1234,"In this poignant, funny follow-up to his fable...",1008,TED2010,1265414400,57,Ken Robinson,Ken Robinson: Bring on the learning revolution!,1,1274691960,"[{'id': 7, 'name': 'Funny', 'count': 3000}, {'...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Author/educator,"['TED Brain Trust', 'children', 'creativity', ...",Bring on the learning revolution!,https://www.ted.com/talks/sir_ken_robinson_bri...,7266316
833,473,"In this talk from RSA Animate, Sir Ken Robinso...",700,RSA Animate,1287014400,0,Ken Robinson,Ken Robinson: Changing education paradigms,1,1292773140,"[{'id': 24, 'name': 'Persuasive', 'count': 145...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['TED Brain Trust', 'business', 'children', 'd...",Changing education paradigms,https://www.ted.com/talks/ken_robinson_changin...,1854997
1386,329,When most well-intentioned aid workers hear of...,1029,TEDxEQChCh,1346457600,35,Ernesto Sirolli,Ernesto Sirolli: Want to help someone? Shut up...,1,1353946523,"[{'id': 24, 'name': 'Persuasive', 'count': 110...","[{'id': 157, 'hero': 'https://pe.tedcdn.com/im...",Sustainable development expert,"['TEDx', 'business', 'global development', 'gl...",Want to help someone? Shut up and listen!,https://www.ted.com/talks/ernesto_sirolli_want...,2829484
1502,634,Sir Ken Robinson outlines 3 principles crucial...,1151,TED Talks Education,1366675200,43,Ken Robinson,Ken Robinson: How to escape education's death ...,1,1368198532,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Author/educator,"['culture', 'education', 'student', 'teaching'...",How to escape education's death valley,https://www.ted.com/talks/ken_robinson_how_to_...,6657858
1802,59,Sir Tim Berners-Lee invented the World Wide We...,403,TED2014,1394582400,29,Tim Berners-Lee,Tim Berners-Lee: A Magna Carta for the web,1,1408375118,"[{'id': 8, 'name': 'Informative', 'count': 174...","[{'id': 484, 'hero': 'https://pe.tedcdn.com/im...",Inventor,"['Internet', 'global issues', 'open-source', '...",A Magna Carta for the web,https://www.ted.com/talks/tim_berners_lee_a_ma...,1054600
1978,64,"The founder of Sirius XM satellite radio, Mart...",1264,TED2015,1426636800,23,Martine Rothblatt,"Martine Rothblatt: My daughter, my wife, our r...",1,1431961167,"[{'id': 10, 'name': 'Inspiring', 'count': 238}...","[{'id': 1658, 'hero': 'https://pe.tedcdn.com/i...",Transhumanist,"['Gender spectrum', 'Transgender', 'biotech', ...","My daughter, my wife, our robot, and the quest...",https://www.ted.com/talks/martine_rothblatt_my...,1304737
2192,61,Trust: How do you earn it? Banks use credit sc...,491,TED2016,1455494400,25,Shivani Siroya,Shivani Siroya: A smart loan for people with n...,1,1461596412,"[{'id': 1, 'name': 'Beautiful', 'count': 169},...","[{'id': 79, 'hero': 'https://pe.tedcdn.com/ima...",Mobile finance entrepreneur,"['TED Fellows', 'business', 'community', 'econ...",A smart loan for people with no credit history...,https://www.ted.com/talks/shivani_siroya_a_sma...,1437353
2503,20,How smart can our machines make us? Tom Gruber...,586,TED2017,1492992000,6,Tom Gruber,"Tom Gruber: How AI can enhance our memory, wor...",1,1502116750,"[{'id': 8, 'name': 'Informative', 'count': 109...","[{'id': 2671, 'hero': 'https://pe.tedcdn.com/i...",AI product designer,"['AI', 'collaboration', 'computers', 'intellig...","How AI can enhance our memory, work and social...",https://www.ted.com/talks/tom_gruber_how_ai_ca...,1139827

In [25]:
df [ df['description'].str.contains(r'\bSir\b') ] #正規化表示文字

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
54,203,"Speaking as both an astronomer and ""a concerne...",1046,TEDGlobal 2005,1121299200,29,Martin Rees,Martin Rees: Is this our final century?,1,1168992660,"[{'id': 1, 'name': 'Beautiful', 'count': 214},...","[{'id': 167, 'hero': 'https://pe.tedcdn.com/im...",Astrophysicist,"['astronomy', 'climate change', 'complexity', ...",Is this our final century?,https://www.ted.com/talks/martin_rees_asks_is_...,2121177
692,1234,"In this poignant, funny follow-up to his fable...",1008,TED2010,1265414400,57,Ken Robinson,Ken Robinson: Bring on the learning revolution!,1,1274691960,"[{'id': 7, 'name': 'Funny', 'count': 3000}, {'...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Author/educator,"['TED Brain Trust', 'children', 'creativity', ...",Bring on the learning revolution!,https://www.ted.com/talks/sir_ken_robinson_bri...,7266316
833,473,"In this talk from RSA Animate, Sir Ken Robinso...",700,RSA Animate,1287014400,0,Ken Robinson,Ken Robinson: Changing education paradigms,1,1292773140,"[{'id': 24, 'name': 'Persuasive', 'count': 145...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['TED Brain Trust', 'business', 'children', 'd...",Changing education paradigms,https://www.ted.com/talks/ken_robinson_changin...,1854997
1502,634,Sir Ken Robinson outlines 3 principles crucial...,1151,TED Talks Education,1366675200,43,Ken Robinson,Ken Robinson: How to escape education's death ...,1,1368198532,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Author/educator,"['culture', 'education', 'student', 'teaching'...",How to escape education's death valley,https://www.ted.com/talks/ken_robinson_how_to_...,6657858
1802,59,Sir Tim Berners-Lee invented the World Wide We...,403,TED2014,1394582400,29,Tim Berners-Lee,Tim Berners-Lee: A Magna Carta for the web,1,1408375118,"[{'id': 8, 'name': 'Informative', 'count': 174...","[{'id': 484, 'hero': 'https://pe.tedcdn.com/im...",Inventor,"['Internet', 'global issues', 'open-source', '...",A Magna Carta for the web,https://www.ted.com/talks/tim_berners_lee_a_ma...,1054600

In [29]:
filter_df = df[ df['description'].str.contains(r'\bSir\b') ]
filter_df

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
54,203,"Speaking as both an astronomer and ""a concerne...",1046,TEDGlobal 2005,1121299200,29,Martin Rees,Martin Rees: Is this our final century?,1,1168992660,"[{'id': 1, 'name': 'Beautiful', 'count': 214},...","[{'id': 167, 'hero': 'https://pe.tedcdn.com/im...",Astrophysicist,"['astronomy', 'climate change', 'complexity', ...",Is this our final century?,https://www.ted.com/talks/martin_rees_asks_is_...,2121177
692,1234,"In this poignant, funny follow-up to his fable...",1008,TED2010,1265414400,57,Ken Robinson,Ken Robinson: Bring on the learning revolution!,1,1274691960,"[{'id': 7, 'name': 'Funny', 'count': 3000}, {'...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Author/educator,"['TED Brain Trust', 'children', 'creativity', ...",Bring on the learning revolution!,https://www.ted.com/talks/sir_ken_robinson_bri...,7266316
833,473,"In this talk from RSA Animate, Sir Ken Robinso...",700,RSA Animate,1287014400,0,Ken Robinson,Ken Robinson: Changing education paradigms,1,1292773140,"[{'id': 24, 'name': 'Persuasive', 'count': 145...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['TED Brain Trust', 'business', 'children', 'd...",Changing education paradigms,https://www.ted.com/talks/ken_robinson_changin...,1854997
1502,634,Sir Ken Robinson outlines 3 principles crucial...,1151,TED Talks Education,1366675200,43,Ken Robinson,Ken Robinson: How to escape education's death ...,1,1368198532,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Author/educator,"['culture', 'education', 'student', 'teaching'...",How to escape education's death valley,https://www.ted.com/talks/ken_robinson_how_to_...,6657858
1802,59,Sir Tim Berners-Lee invented the World Wide We...,403,TED2014,1394582400,29,Tim Berners-Lee,Tim Berners-Lee: A Magna Carta for the web,1,1408375118,"[{'id': 8, 'name': 'Informative', 'count': 174...","[{'id': 484, 'hero': 'https://pe.tedcdn.com/im...",Inventor,"['Internet', 'global issues', 'open-source', '...",A Magna Carta for the web,https://www.ted.com/talks/tim_berners_lee_a_ma...,1054600

In [31]:
filter_df.to_csv('filter.csv', encoding = 'utf-8', index = False)

In [32]:
pd.read_csv('filter.csv', encoding = 'utf-8')

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,203,"Speaking as both an astronomer and ""a concerne...",1046,TEDGlobal 2005,1121299200,29,Martin Rees,Martin Rees: Is this our final century?,1,1168992660,"[{'id': 1, 'name': 'Beautiful', 'count': 214},...","[{'id': 167, 'hero': 'https://pe.tedcdn.com/im...",Astrophysicist,"['astronomy', 'climate change', 'complexity', ...",Is this our final century?,https://www.ted.com/talks/martin_rees_asks_is_...,2121177
2,1234,"In this poignant, funny follow-up to his fable...",1008,TED2010,1265414400,57,Ken Robinson,Ken Robinson: Bring on the learning revolution!,1,1274691960,"[{'id': 7, 'name': 'Funny', 'count': 3000}, {'...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Author/educator,"['TED Brain Trust', 'children', 'creativity', ...",Bring on the learning revolution!,https://www.ted.com/talks/sir_ken_robinson_bri...,7266316
3,473,"In this talk from RSA Animate, Sir Ken Robinso...",700,RSA Animate,1287014400,0,Ken Robinson,Ken Robinson: Changing education paradigms,1,1292773140,"[{'id': 24, 'name': 'Persuasive', 'count': 145...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['TED Brain Trust', 'business', 'children', 'd...",Changing education paradigms,https://www.ted.com/talks/ken_robinson_changin...,1854997
4,634,Sir Ken Robinson outlines 3 principles crucial...,1151,TED Talks Education,1366675200,43,Ken Robinson,Ken Robinson: How to escape education's death ...,1,1368198532,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Author/educator,"['culture', 'education', 'student', 'teaching'...",How to escape education's death valley,https://www.ted.com/talks/ken_robinson_how_to_...,6657858
5,59,Sir Tim Berners-Lee invented the World Wide We...,403,TED2014,1394582400,29,Tim Berners-Lee,Tim Berners-Lee: A Magna Carta for the web,1,1408375118,"[{'id': 8, 'name': 'Informative', 'count': 174...","[{'id': 484, 'hero': 'https://pe.tedcdn.com/im...",Inventor,"['Internet', 'global issues', 'open-source', '...",A Magna Carta for the web,https://www.ted.com/talks/tim_berners_lee_a_ma...,1054600

In [35]:
df.drop(['url', 'views'], axis=1) #axis= 0 刪除列 ， axis= 1 刪除行

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2545,17,"Between 2008 and 2016, the United States depor...",476,TED2017,1496707200,4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,1,1505851216,"[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...
2546,6,How can you study Mars without a spaceship? He...,290,TED2017,1492992000,3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,1,1505919737,"[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth
2547,10,Science fiction visions of the future show us ...,651,TED2017,1492992000,1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,1,1506006095,"[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...
2548,32,In an unmissable talk about race and politics ...,1100,TEDxMileHigh,1499472000,1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,1,1506024042,"[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right
2549,8,With more than half of the world population li...,519,TED2017,1492992000,1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,1,1506092422,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...

In [37]:
df ['film_date']

0       1140825600
1       1140825600
2       1140739200
3       1140912000
4       1140566400
           ...
2545    1496707200
2546    1492992000
2547    1492992000
2548    1499472000
2549    1492992000
Name: film_date, Length: 2550, dtype: int64

In [43]:
from datetime import datetime   #轉換西元時間模組
import pytz
print('原始:', df['film_date'][0])

print('轉換（當地時間）:', datetime.fromtimestamp(df['film_date'][0]) )
print('轉換（標準時間）:', datetime.utcfromtimestamp(df['film_date'][0]) )

原始: 1140825600
轉換（當地時間）: 2006-02-25 08:00:00
轉換（標準時間）: 2006-02-25 00:00:00

In [45]:
def timeflow(data):
    return str(datetime.utcfromtimestamp(data))
df['film_date'].apply(timeflow)

0       2006-02-25 00:00:00
1       2006-02-25 00:00:00
2       2006-02-24 00:00:00
3       2006-02-26 00:00:00
4       2006-02-22 00:00:00
               ...
2545    2017-06-06 00:00:00
2546    2017-04-24 00:00:00
2547    2017-04-24 00:00:00
2548    2017-07-08 00:00:00
2549    2017-04-24 00:00:00
Name: film_date, Length: 2550, dtype: object

In [51]:
df['film_date(datetime)'] = df['film_date'].apply(timeflow)
df[ ['film_date', 'film_date(datetime)']]   #設定回原表格

       film_date  film_date(datetime)
0     1140825600  2006-02-25 00:00:00
1     1140825600  2006-02-25 00:00:00
2     1140739200  2006-02-24 00:00:00
3     1140912000  2006-02-26 00:00:00
4     1140566400  2006-02-22 00:00:00
...          ...                  ...
2545  1496707200  2017-06-06 00:00:00
2546  1492992000  2017-04-24 00:00:00
2547  1492992000  2017-04-24 00:00:00
2548  1499472000  2017-07-08 00:00:00
2549  1492992000  2017-04-24 00:00:00

[2550 rows x 2 columns]

In [53]:
def tag_filter(element):
    tag_list = eval(element) #element 每一格的資料
    if 'children' in tag_list:
        return True
bool_filter = df['tags'].apply(tag_filter)
bool_filter

0       True
1       None
2       None
3       None
4       None
        ...
2545    None
2546    None
2547    None
2548    None
2549    None
Name: tags, Length: 2550, dtype: object

In [61]:
df[bool_filter] [['description', 'tags']]

,description,tags
4,You've never seen data presented like this. Wi...,"['Africa', 'Asia', 'Google', 'demo', 'economic..."
117,Researcher Hans Rosling uses his cool data too...,"['Africa', 'Asia', 'Google', 'economics', 'glo..."
359,Reporter Jennifer 8. Lee talks about her hunt ...,"['Asia', 'business', 'culture', 'exploration',..."
448,"Nandan Nilekani, the visionary co-founder of o...","['Asia', 'business', 'economics', 'future', 'g..."
484,TED Fellow Sophal Ear shares the compelling st...,"['Asia', 'adventure', 'history', 'storytelling..."
502,Talking at the US State Department this summer...,"['Africa', 'Asia', 'data', 'global development..."
512,Vishal Vaid and his band explore a traditional...,"['Asia', 'beauty', 'culture', 'history', 'musi..."
523,Many people think the lines on the map no long...,"['Asia', 'economics', 'global issues', 'histor..."
558,Hans Rosling was a young guest student in Indi...,"['Asia', 'economics', 'health', 'india', 'stat..."
567,Sunitha Krishnan has dedicated her life to res...,"['Asia', 'Slavery', 'children', 'global issues..."
573,"Ryan Lobo has traveled the world, taking photo...","['Asia', 'art', 'humanity', 'photography', 'st..."
577,Shaffi Mather explains why he left his first c...,"['Asia', 'TED Fellows', 'crime', 'entrepreneur..."
597,Collector Ravin Agrawal delivers a glowing int...,"['Asia', 'art', 'design', 'future', 'india']"
854,"Speaking at a TED Salon in London, Martin Jacq...","['Asia', 'business', 'china', 'culture', 'econ..."
1011,Economist Yasheng Huang compares China to Indi...,"['Asia', 'culture', 'democracy', 'economics', ..."
1027,"Yang Lan, a journalist and entrepreneur who's ...","['Asia', 'china', 'economics', 'global issues'..."
1204,TED Fellow Abigail Washburn wanted to be a law...,"['Asia', 'TED Fellows', 'china', 'culture', 'e..."
1302,Michael Anti (aka Jing Zhao) has been blogging...,"['Asia', 'china', 'global issues', 'journalism..."
1305,In the wake of the 2011 Japanese earthquake an...,"['Asia', 'culture', 'disaster relief', 'memory..."
1327,"In the ongoing debate about globalization, wha...","['Asia', 'china', 'consumerism', 'culture', 'e..."
1460,"As a child growing up in North Korea, Hyeonseo...","['Asia', 'culture', 'family', 'global issues']"
1537,It's a standard assumption in the West: As a s...,"['Asia', 'business', 'china', 'democracy', 'gl..."
1615,Dong Woo Jang has an unusual after school hobb...,"['Asia', 'culture', 'demo', 'invention']"
1621,The developed world holds up the ideals of cap...,"['Africa', 'Asia', 'china', 'democracy', 'econ..."
1948,"The former prime minister of Australia, Kevin ...","['Asia', 'United States', 'china', 'politics']"
2310,Americanization and globalization have basical...,"['Africa', 'Asia', 'Europe', 'Foreign Policy',..."

In [57]:
def tag_filter(element, filter_tag):
    tag_list = eval(element)
    if filter_tag in tag_list:
        return True
    else:
        return False
bool_filter = df['tags'].apply(tag_filter, filter_tag = 'Asia')
bool_filter

0       False
1       False
2       False
3       False
4        True
        ...
2545    False
2546    False
2547    False
2548    False
2549    False
Name: tags, Length: 2550, dtype: bool

In [60]:
df[bool_filter] [['description', 'tags']]

,description,tags
4,You've never seen data presented like this. Wi...,"['Africa', 'Asia', 'Google', 'demo', 'economic..."
117,Researcher Hans Rosling uses his cool data too...,"['Africa', 'Asia', 'Google', 'economics', 'glo..."
359,Reporter Jennifer 8. Lee talks about her hunt ...,"['Asia', 'business', 'culture', 'exploration',..."
448,"Nandan Nilekani, the visionary co-founder of o...","['Asia', 'business', 'economics', 'future', 'g..."
484,TED Fellow Sophal Ear shares the compelling st...,"['Asia', 'adventure', 'history', 'storytelling..."
502,Talking at the US State Department this summer...,"['Africa', 'Asia', 'data', 'global development..."
512,Vishal Vaid and his band explore a traditional...,"['Asia', 'beauty', 'culture', 'history', 'musi..."
523,Many people think the lines on the map no long...,"['Asia', 'economics', 'global issues', 'histor..."
558,Hans Rosling was a young guest student in Indi...,"['Asia', 'economics', 'health', 'india', 'stat..."
567,Sunitha Krishnan has dedicated her life to res...,"['Asia', 'Slavery', 'children', 'global issues..."
573,"Ryan Lobo has traveled the world, taking photo...","['Asia', 'art', 'humanity', 'photography', 'st..."
577,Shaffi Mather explains why he left his first c...,"['Asia', 'TED Fellows', 'crime', 'entrepreneur..."
597,Collector Ravin Agrawal delivers a glowing int...,"['Asia', 'art', 'design', 'future', 'india']"
854,"Speaking at a TED Salon in London, Martin Jacq...","['Asia', 'business', 'china', 'culture', 'econ..."
1011,Economist Yasheng Huang compares China to Indi...,"['Asia', 'culture', 'democracy', 'economics', ..."
1027,"Yang Lan, a journalist and entrepreneur who's ...","['Asia', 'china', 'economics', 'global issues'..."
1204,TED Fellow Abigail Washburn wanted to be a law...,"['Asia', 'TED Fellows', 'china', 'culture', 'e..."
1302,Michael Anti (aka Jing Zhao) has been blogging...,"['Asia', 'china', 'global issues', 'journalism..."
1305,In the wake of the 2011 Japanese earthquake an...,"['Asia', 'culture', 'disaster relief', 'memory..."
1327,"In the ongoing debate about globalization, wha...","['Asia', 'china', 'consumerism', 'culture', 'e..."
1460,"As a child growing up in North Korea, Hyeonseo...","['Asia', 'culture', 'family', 'global issues']"
1537,It's a standard assumption in the West: As a s...,"['Asia', 'business', 'china', 'democracy', 'gl..."
1615,Dong Woo Jang has an unusual after school hobb...,"['Asia', 'culture', 'demo', 'invention']"
1621,The developed world holds up the ideals of cap...,"['Africa', 'Asia', 'china', 'democracy', 'econ..."
1948,"The former prime minister of Australia, Kevin ...","['Asia', 'United States', 'china', 'politics']"
2310,Americanization and globalization have basical...,"['Africa', 'Asia', 'Europe', 'Foreign Policy',..."